apiVersion: v1
kind: Secret
metadata:
  name: devhub-api-prod-secrets
  namespace: devhub-prod
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://USER:PASSWORD@cluster.mongodb.net/devhub-prod"
  JWT_SECRET: "CHANGE_THIS_SECRET"
  JWT_REFRESH_SECRET: "CHANGE_THIS_REFRESH_SECRET"
