apiVersion: v1
kind: Service
metadata:
  name: devhub-api-prod-service
  namespace: devhub-prod
spec:
  selector:
    app: devhub-api
    environment: production
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
