apiVersion: v1
kind: Secret
metadata:
  name: devhub-api-cert-secrets
  namespace: devhub-cert
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://USER:PASSWORD@cluster.mongodb.net/devhub-cert"
  JWT_SECRET: "CHANGE_THIS_SECRET"
  JWT_REFRESH_SECRET: "CHANGE_THIS_REFRESH_SECRET"
