apiVersion: v1
kind: Service
metadata:
  name: devhub-api-cert-service
  namespace: devhub-cert
spec:
  selector:
    app: devhub-api
    environment: certification
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
